### PR TITLE
Schema validation error for tx type 7 - Closes #174

### LINKED ISSUE #174: Schema validation error for tx type 7
@lsilvs commented on [Tue Dec 03 2019](https://github.com/LiskHQ/lisk-sdk/issues/4585)

### Expected behavior
Expect to validate transaction `id = 8742556801784407667` on mainnet

### Actual behavior
It fails with the following error:

```
err: [
      {
        "message": "'.amount' should be string",
        "name": "TransactionError",
        "id": "8742556801784407667",
        "dataPath": ".amount"
      }
    ]
```

### Steps to reproduce
Start syncing with mainnet and wait until block height `808831`

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0.0-alpha.2`

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
`InTransferTransaction` and `OutTransferTransaction` expect asset.amount to be string but the conversion was missing from `assetToJSON` method similar to how it's done for `TransferTransaction`

### How did I fix it?
By converting `amount` to string inside `assetToJSON` for both `InTransferTransaction` and `OutTransferTransaction`

### How to test it?
Start syncing with mainnet. It should pass block height `808831`

### Review checklist

* The PR resolves #174
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: src/transactions/6_in_transfer_transaction.ts [hunk 1]
```diff
@@ -145,7 +145,10 @@ export class InTransferTransaction extends BaseTransaction {
 	}
 
 	public assetToJSON(): object {
-		return this.asset;
+		return {
```
Comment (limiaspasdaniel) [inline src/transactions/6_in_transfer_transaction.ts]: maybe 
```
return  {
  ...this.asset,
  amount: this.asset.amount.toString()
```
?

File: src/transactions/7_out_transfer_transaction.ts [hunk 2]
```diff
@@ -156,7 +156,11 @@ export class OutTransferTransaction extends BaseTransaction {
 	}
 
 	public assetToJSON(): object {
-		return this.asset;
+		return {
+			amount: this.asset.amount.toString(),
```
Comment (limiaspasdaniel) [inline src/transactions/7_out_transfer_transaction.ts]: And same here :)

File: src/transactions/6_in_transfer_transaction.ts (hunk 1 above)
Comment (lsilvs) [reply src/transactions/6_in_transfer_transaction.ts]: Done

File: src/transactions/7_out_transfer_transaction.ts (hunk 2 above)
Comment (lsilvs) [reply src/transactions/7_out_transfer_transaction.ts]: Done
