### PR TITLE
Call 'lisk' instead of 'lisky'

### LINKED ISSUE #136: Lisk.sh needs update
lisk.sh help returns:
```
start_node                         Starts a Nodejs process for Lisk
start                                 Starts the Nodejs process and PostgreSQL Database for Lisk
stop_node                             Stops a Nodejs process for Lisk
stop                                  Stop the Nodejs process and PostgreSQL Database for Lisk
reload                                Restarts the Nodejs process for Lisk
rebuild [-u URL] [-f file.db.gz] [-0] Rebuilds the PostgreSQL database
start_db                              Starts the PostgreSQL database
stop_db                               Stops the PostgreSQL database
coldstart                             Creates the PostgreSQL database and configures config.json for Lisk
lisk                                  Launches Lisk-commander
logs                                  Displays and tails logs for Lisk
status                                Displays the status of the PID associated with Lisk
help                                  Displays this message
```

Running ```lisk.sh lisk``` to launch Lisk-commander returns Error: Unrecognized command.

Looking at the source, there is ```lisky``` option (at line 502) which should run commander but calling ```lisky``` option calls lisky() function which seems to be renamed to lisk() (on line 309)

Replacing ```lisky``` with ```lisk``` on line 503 fixes the error.

P.S.
I could create the patch myself, but I'm not sure whether you want the option to be called ```lisky``` or ```lisk```.

### PR DESCRIPTION
**Pull request by Nazgolze**
### What was the problem?
This PR resolves #136 
lisk.sh does not accept `lisky`, `lisk` or `commander` to call lisk-commander
### How was it solved?

The intended `or` logic was inside of quotes and never got evaluated. This has been changed so that only lisky, lisk and commander are quoted separately
### How was it tested?

I ran './lisk.sh lisky', './lisk.sh lisk' and './lisk.sh commander' separately and verified that it worked.

### CODE REVIEW

**Comment by Nazgolze** [comment]
Unfortunately, I didn't put enough thought into this :sweat_smile:

As is, it made more sense when lisk-commander was an interactive shell and didn't have to take command line arguments.

But now it's necessary to allow it to take arguments or else all it does is show help.
I have a commit ready that will do exactly this, but because of how lisk.sh works, it's going to strip the coloring and also tee all of the output to lisk.out

**Comment by fchavant** [comment]
Maybe it's not worth the effort then? How about simply showing an explanatory message asking the user to run `lisk` directly?

**Comment by fchavant** [comment]
Maybe it's not worth the effort then? How about simply showing an explanatory message asking the user to run `lisk` directly?

**Comment by Nazgolze** [comment]
> Maybe it's not worth the effort then? How about simply showing an explanatory message asking the user to run `lisk` directly?

Added, in a "best of both worlds" approach

```
lisk@mrbox:~/lisk-beta$ bash lisk.sh lisk version
Lisk configured for betanet

Note: invoking Lisk Commander from lisk.sh is deprecated and will be removed in a future version
      To run the included version of Lisk Commander directly, 'source env.sh' and then
      'bin/lisk'

lisk-commander/3.0.2 linux-x64 node-v12.14.1
```
vs
```
lisk@mrbox:~/lisk-beta$ bin/lisk version
lisk-commander/3.0.2 linux-x64 node-v12.14.1
```

**Comment by Nazgolze** [comment]
> > Maybe it's not worth the effort then? How about simply showing an explanatory message asking the user to run `lisk` directly?
> 
> Added, in a "best of both worlds" approach
> 
> ```
> lisk@mrbox:~/lisk-beta$ bash lisk.sh lisk version
> Lisk configured for betanet
> 
> Note: invoking Lisk Commander from lisk.sh is deprecated and will be removed in a future version
>       To run the included version of Lisk Commander directly, 'source env.sh' and then
>       'bin/lisk'
> 
> lisk-commander/3.0.2 linux-x64 node-v12.14.1
> ```
> 
> vs
> 
> ```
> lisk@mrbox:~/lisk-beta$ bin/lisk version
> lisk-commander/3.0.2 linux-x64 node-v12.14.1
> ```

The first one btw takes 3.2 seconds and the second one 0.16 seconds. You *really* don' want to invoke Lisk Commander with lisk.sh

File: build/target/lisk.sh [hunk 1]
```diff
@@ -499,8 +499,13 @@ case $1 in
 "logs")
 	tail_logs
 	;;
-"lisky|lisk|commander")
-	lisk
+"lisky"|"lisk"|"commander")
+	echo
```
Comment (fchavant) [inline build/target/lisk.sh]: Shouldn't this go to stderr to be separable from the output of commander?

Comment (Nazgolze) [reply build/target/lisk.sh]: that would be nicer, yes. will fix that up :+1:

Comment (Nazgolze) [reply build/target/lisk.sh]: negative. The `exec 2>&1` further up forces it all to stdout anyway

Comment (fchavant) [reply build/target/lisk.sh]: :(

**Comment by fchavant** [comment]
@ManuGowda you've got to use a tarball from https://downloads.lisk.io/lisk/betanet/3.0.0-beta.0/ and replace `lisk.sh` with the one from the PR (i.e. it will not work standalone, you need the whole binary release)

**Comment by ManuGowda** [comment]
Thanks @fchavant , I tested it and it works 
```
➜  lisk-3.0.0-beta.0-Darwin-x86_64 git:(136-call-lisky-addendum) ✗ ./lisk.sh commander
Lisk configured for betanet

Note: invoking Lisk Commander from lisk.sh is deprecated and will be removed in a future version
      To run the included version of Lisk Commander directly, 'source env.sh' and then
      'bin/lisk'

A command line interface for Lisk

VERSION
  lisk-commander/3.0.2 darwin-x64 node-v12.14.1
v
```

**Comment by ManuGowda** [comment]
@Nazgolze would be also nice to have a PR for next hotfix? or an issue just to remember when we patch next release, what do you think?
