### PR TITLE
IPC Socket client connection timeout - Closes #351

### LINKED ISSUE #351: IPC Socket client connection timeout
### Expected behavior

Should be able to run stress test for any given path.

### Actual behavior

```
Error: IPC Socket client connection timeout. Please check if IPC server is running.
    at Timeout._onTimeout (/Users/manu/lisk_ecosystem/sdk-core-lips/lisk-sdk/framework/src/controller/ipc/ipc_client.ts:47:6)
```

### Steps to reproduce

`npm run test`

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #351 

### How was it solved?

- Updated data path

### How was it tested?

- Added readme

### CODE REVIEW

File: test/scripts/stress_test.ts [hunk 1]
```diff
@@ -38,23 +39,22 @@ const chunkArray = (myArray: PassphraseAndKeys[], chunkSize = TRANSACTIONS_PER_A
...
 	};
 };
 
 const startIPCChannel = async (): Promise<IPCChannel> => {
 	const events: string[] = [];
 	const actions = {};
-	// rootPath: check configuration(network specific, devnet, alphanet, testnet, mainnet) to find rootPath name
-	// label: check configuration(network specific, devnet, alphanet, testnet, mainnet) to find label name
-
-	const socketsPath = getSocketsPath('/Users/manu/.lisk', NETWORK);
```
Comment (shuse2) [inline test/scripts/stress_test.ts:57]: 😮

**Review by shuse2 — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]
