### PR TITLE
Fix symlink path - Closes #407

### LINKED ISSUE #407: Command sdk:link is broken when parent directory is provided
### Expected behavior

- Given parent directory `../` or home directory `~`, the `sdk:link` command must resolve the path correctly to link the SDK.

### Actual behavior

The `./bin/run sdk:link ../lisk-sdk/sdk` is broken

### Steps to reproduce

- Build lisk-sdk and follow procedure to link sdk
- Navigate to lisk-core and run `./bin/run sdk:link ../lisk-sdk/sdk`
- Run `npm run build` in lisk-core 
- The build fails

### Which version(s) does this affect? (Environment, OS, etc...)
development, 3.0.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #407 

### How was it solved?

- Update symlink to reference from the node_modules, where it was the path from the root folder

### How was it tested?

- rm -rf node_modules
- npm i --registry https://npm.lisk.io
- ./bin/run sdk:link ../lisk-sdk/sdk
- npm run build

### CODE REVIEW

File: src/commands/sdk/link.ts [hunk 1]
```diff
@@ -39,8 +39,9 @@ export default class LinkCommand extends Command {
 
 		const sdkLocalPath = join(__dirname, '../../../', 'node_modules', 'lisk-sdk');
 
+		const targetSDKFolderFromNodeModule = join('../', targetSDKFolder);
 		removeSync(sdkLocalPath);
-		symlinkSync(targetSDKFolder, sdkLocalPath);
+		await symlink(targetSDKFolderFromNodeModule, sdkLocalPath);
 		this.log(`Linked '${targetSDKFolder as string}' to '${sdkLocalPath}'`);
```
Comment (ManuGowda) [inline src/commands/sdk/link.ts:45]:
```suggestion
		this.log(`Linked '${targetSDKFolderFromNodeModule}' to '${sdkLocalPath}'`);
```

**Review by pablitovicente — APPROVED** [review]

File: src/commands/sdk/link.ts (hunk 1 above)
Comment (shuse2) [reply src/commands/sdk/link.ts:45]: I think from user, `targetSDKFolder` is probably correct path (since it's the path they typed

**Review by ManuGowda — APPROVED** [review]
