### PR TITLE
Blockchain download command outputs file in incorrect path - Closes #359

### LINKED ISSUE #359: Blockchain download command outputs file in incorrect path
### Expected behavior

The blockchain file should be downloaded to specified path `-o` and by default to current directory.

### Actual behavior

```
./bin/run blockchain:download -u https://downloads.lisk.io/lisk/beta/blockchain.db.gz -n devnet -o /tmp
```
Downloads to `/tmp/downloads.lisk.io/lisk/beta/blockchain.db.gz`

```
./bin/run blockchain:download -u https://downloads.lisk.io/lisk/beta/blockchain.db.gz -n devnet
```
Downloads to  `~/.lisk/default` if `-o` not specified

### Steps to reproduce
- Run command
```
./bin/run blockchain:download -u https://downloads.lisk.io/lisk/beta/blockchain.db.gz -n devnet -o /tmp
```

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #INSERT_ISSUE_NUMBER

### How was it solved?

- By default download to CWD
- Download file to specified path

### How was it tested?

- For default path `./bin/run blockchain:download -u https://downloads.lisk.io/lisk/beta/blockchain.db.gz -n devnet`
- For output path `./bin/run blockchain:download -u https://downloads.lisk.io/lisk/beta/blockchain.db.gz -n devnet -o /tmp`

### CODE REVIEW

File: src/commands/blockchain/download.ts [hunk 1]
```diff
@@ -38,8 +38,8 @@ export default class DownloadCommand extends Command {
 		output: flagParser.string({
 			char: 'o',
 			description:
-				'Directory path to specify where snapshot is downloaded. Environment variable "LISK_DATA_PATH" can also be used.',
-			env: 'LISK_DATA_PATH',
+				'Directory path to specify where snapshot is downloaded. By default outputs the files to current working directory.',
+			default: '.',
```
Comment (shuse2) [inline src/commands/blockchain/download.ts:42]: default should be `process.cwd()`

File: src/utils/download.ts [hunk 2]
```diff
@@ -27,12 +27,11 @@ export interface FileInfo {
 export const getDownloadedFileInfo = (url: string, downloadDir: string): FileInfo => {
 	const pathWithoutProtocol = url.replace(/(^\w+:|^)\/\//, '').split('/');
 	const fileName = pathWithoutProtocol.pop() as string;
-	const fileDir = `${downloadDir}/${pathWithoutProtocol.join('/')}`;
-	const filePath = `${fileDir}/${fileName}`;
+	const filePath = `${downloadDir}/${fileName}`;
```
Comment (shuse2) [inline src/utils/download.ts:30]: prefer to use `path.join`

**Review by shuse2 — CHANGES_REQUESTED** [review]

**Review by shuse2 — APPROVED** [review]
